server:
  port: 8080
spring:
  application:
    name: sample-restfull
  datasource:
    url: jdbc:postgresql://localhost:5432/SAMPLE_DB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: public
